<a href="https://colab.research.google.com/github/eldiinzhanyy/batys-bankrupts-analysis/blob/main/bezrabotica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Т-14-23-Г_рус.xls to Т-14-23-Г_рус (1).xls

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Т-14-23-Г_рус.xls", sheet_name="13", header=None)

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,13. Основные индикаторы рынка труда по районам...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"Рабочая сила, человек","Доля рабочей силы в численности населения, в п...","Занятое население, человек",В том числе,NaN,"Безработное население, человек","Уровень безрабо-тицы, в процентах","Уровень молодежной безработицы, % (в возрасте ...","Лица, не входящие в состав рабочей силы, человек","Доля лиц, не входящие в состав в рабочей силы ..."
2,NaN,NaN,NaN,NaN,наемные работники,самостоятельно занятые работники,NaN,NaN,NaN,NaN,NaN
3,Все население,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Западно-Казахстанская область,357116,70,340153,251209,88944,16963,4.7,3.6,153305,30

In [5]:
df = pd.read_excel("Т-14-23-Г_рус.xls", sheet_name="13", skiprows=3, header=None)

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,Все население,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Западно-Казахстанская область,357116.0,70.0,340153.0,251209.0,88944.0,16963.0,4.7,3.6,153305.0,30.0
2,Уральск г.а.,179022.0,66.3,170751.0,140406.0,30345.0,8271.0,4.6,3.4,91170.0,33.7
3,Акжаикский район,18959.0,75.1,18069.0,10911.0,7158.0,890.0,4.7,4.2,6298.0,24.9
4,Бурлинский район,32320.0,76.0,30889.0,26120.0,4769.0,1431.0,4.4,3.5,10212.0,24.0

In [7]:
df.columns = ["район", "рабочая_сила", "доля_рабочей_силы", "занятое_население", "наемные_работники", "самозанятые", "безработное_население",  "уровень_безработицы", "уровень_молодежной_безработицы", "вне_рабочей_силы", "доля_вне_рабочей_силы"]

In [8]:
df.head()

,район,рабочая_сила,доля_рабочей_силы,занятое_население,наемные_работники,самозанятые,безработное_население,уровень_безработицы,уровень_молодежной_безработицы,вне_рабочей_силы,доля_вне_рабочей_силы
0,Все население,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Западно-Казахстанская область,357116.0,70.0,340153.0,251209.0,88944.0,16963.0,4.7,3.6,153305.0,30.0
2,Уральск г.а.,179022.0,66.3,170751.0,140406.0,30345.0,8271.0,4.6,3.4,91170.0,33.7
3,Акжаикский район,18959.0,75.1,18069.0,10911.0,7158.0,890.0,4.7,4.2,6298.0,24.9
4,Бурлинский район,32320.0,76.0,30889.0,26120.0,4769.0,1431.0,4.4,3.5,10212.0,24.0

In [9]:
df.head(15)

,район,рабочая_сила,доля_рабочей_силы,занятое_население,наемные_работники,самозанятые,безработное_население,уровень_безработицы,уровень_молодежной_безработицы,вне_рабочей_силы,доля_вне_рабочей_силы
0,Все население,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Западно-Казахстанская область,357116.0,70.0,340153.0,251209.0,88944.0,16963.0,4.7,3.6,153305.0,30.0
2,Уральск г.а.,179022.0,66.3,170751.0,140406.0,30345.0,8271.0,4.6,3.4,91170.0,33.7
3,Акжаикский район,18959.0,75.1,18069.0,10911.0,7158.0,890.0,4.7,4.2,6298.0,24.9
4,Бурлинский район,32320.0,76.0,30889.0,26120.0,4769.0,1431.0,4.4,3.5,10212.0,24.0
5,Жангалинский район,10881.0,72.7,10355.0,6296.0,4059.0,526.0,4.8,3.7,4094.0,27.3
6,Жанибекский район,7766.0,76.3,7325.0,4493.0,2832.0,441.0,5.7,4.3,2411.0,23.7
7,Район Бәйтерек,34933.0,73.9,33292.0,19570.0,13722.0,1641.0,4.7,2.9,12309.0,26.1
8,Казталовский район,13498.0,72.0,12739.0,6816.0,5923.0,759.0,5.6,4.2,5249.0,28.0
9,Каратобинский район,6846.0,72.8,6454.0,3985.0,2469.0,392.0,5.7,6,2564.0,27.2
10,Бокейординский район,7351.0,73.5,6939.0,3582.0,3357.0,412.0,5.6,4.7,2651.0,26.5
11,Сырымский район,9110.0,76.9,8669.0,4687.0,3982.0,441.0,4.8,3.4,2733.0,23.1
12,Таскалинский район,8685.0,73.2,8260.0,5251.0,3009.0,425.0,4.9,4.3,3182.0,26.8
13,Теректинский район,21016.0,72.4,20013.0,14848.0,5165.0,1003.0,4.8,4.1,8012.0,27.6
14,Чингирлауский район,6729.0,73.5,6398.0,4244.0,2154.0,331.0,4.9,4.4,2420.0,26.5

In [10]:
df = df.iloc[1:15]

In [11]:
df.tail()

,район,рабочая_сила,доля_рабочей_силы,занятое_население,наемные_работники,самозанятые,безработное_население,уровень_безработицы,уровень_молодежной_безработицы,вне_рабочей_силы,доля_вне_рабочей_силы
10,Бокейординский район,7351.0,73.5,6939.0,3582.0,3357.0,412.0,5.6,4.7,2651.0,26.5
11,Сырымский район,9110.0,76.9,8669.0,4687.0,3982.0,441.0,4.8,3.4,2733.0,23.1
12,Таскалинский район,8685.0,73.2,8260.0,5251.0,3009.0,425.0,4.9,4.3,3182.0,26.8
13,Теректинский район,21016.0,72.4,20013.0,14848.0,5165.0,1003.0,4.8,4.1,8012.0,27.6
14,Чингирлауский район,6729.0,73.5,6398.0,4244.0,2154.0,331.0,4.9,4.4,2420.0,26.5

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 1 to 14
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   район                           14 non-null     object
 1   рабочая_сила                    14 non-null     float64
 2   доля_рабочей_силы               14 non-null     float64
 3   занятое_население               14 non-null     float64
 4   наемные_работники               14 non-null     float64
 5   самозанятые                     14 non-null     float64
 6   безработное_население           14 non-null     float64
 7   уровень_безработицы             14 non-null     float64
 8   уровень_молодежной_безработицы  14 non-null     object
 9   вне_рабочей_силы                14 non-null     float64
 10  доля_вне_рабочей_силы           14 non-null     float64
dtypes: float64(9), object(2)
memory usage: 1.3+ KB

In [13]:
df["уровень_молодежной_безработицы"]

1     3.6
2     3.4
3     4.2
4     3.5
5     3.7
6     4.3
7     2.9
8     4.2
9       6
10    4.7
11    3.4
12    4.3
13    4.1
14    4.4
Name: уровень_молодежной_безработицы, dtype: object

In [14]:
df["уровень_молодежной_безработицы"] = pd.to_numeric(df["уровень_молодежной_безработицы"], errors="coerce")

In [15]:
df["уровень_молодежной_безработицы"].dtype

dtype('float64')

In [16]:
df["уровень_молодежной_безработицы"].isna().sum()

np.int64(0)

In [17]:
df.to_csv("unemployment_zko_clean.csv", index=False, encoding="utf-8-sig")