<a href="https://colab.research.google.com/github/eldiinzhanyy/batys-bankrupts-analysis/blob/main/sqlnalog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('bankrupts_zko_clean.csv')

In [3]:
df.head()

,№,ИИН/БИН,Наименование налогоплательщика,ФИО налогоплательщика,ФИО руководителя,Номер решения суда,Дата решения суда,Год решения
0,1,2.310400e+11,"Товарищество с ограниченной ответственностью""Г...",NaN,ҚАЛИЕВ АЙБОЛАТ ҚҰРМАНҒАЛИҰЛЫ,2713-26-00-2/788,2026-06-22,2026.0
1,2,2.101400e+11,"Товарищество с ограниченной ответственностью""B...",NaN,САГИТОВ ИЛЬДАР РАСТАМОВИЧ,Решение СМЭС по ЗКО №2713-24-00-2/1831,NaN,NaN
2,3,2.001400e+11,"Товарищество с ограниченной ответственностью""Z...",NaN,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/112,2026-03-20,2026.0
3,4,1.909400e+11,"Товарищество с ограниченной ответственностью""R...",NaN,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-26-00-2/178,2026-06-18,2026.0
4,5,1.907400e+11,"Товарищество с ограниченной ответственностью""G...",NaN,КУРМАНГАЛИЕВ АЛДАН ХАБИБУЛЛОВИЧ,2713-22-00-2/1538,2024-10-08,2024.0

In [4]:
import sqlite3

conn = sqlite3.connect("bankrupts.db")
df.to_sql("bankrupts", conn, if_exists="replace", index=False)

56

In [5]:
pd.read_sql("SELECT * FROM bankrupts", conn)

,№,ИИН/БИН,Наименование налогоплательщика,ФИО налогоплательщика,ФИО руководителя,Номер решения суда,Дата решения суда,Год решения
0,1,2.310400e+11,"Товарищество с ограниченной ответственностью""Г...",None,ҚАЛИЕВ АЙБОЛАТ ҚҰРМАНҒАЛИҰЛЫ,2713-26-00-2/788,2026-06-22,2026.0
1,2,2.101400e+11,"Товарищество с ограниченной ответственностью""B...",None,САГИТОВ ИЛЬДАР РАСТАМОВИЧ,Решение СМЭС по ЗКО №2713-24-00-2/1831,None,NaN
2,3,2.001400e+11,"Товарищество с ограниченной ответственностью""Z...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/112,2026-03-20,2026.0
3,4,1.909400e+11,"Товарищество с ограниченной ответственностью""R...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-26-00-2/178,2026-06-18,2026.0
4,5,1.907400e+11,"Товарищество с ограниченной ответственностью""G...",None,КУРМАНГАЛИЕВ АЛДАН ХАБИБУЛЛОВИЧ,2713-22-00-2/1538,2024-10-08,2024.0
5,6,1.906400e+11,"Товарищество с ограниченной ответственностью ""...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2285,2024-10-08,2024.0
6,7,1.803400e+11,"Товарищество с ограниченной ответственностью""B...",None,АМАНГАЛИЕВ ЕРЛАН НУРЛАНОВИЧ,2713-26-00-2/339,2026-06-18,2026.0
7,8,1.709400e+11,"Товарищество с ограниченной ответственностью""Ч...",None,ЖАКАТАЕВ БАХЫТЖАН КАЙЫРЛИЕВИЧ,2713-24-00-2/1004,2024-10-08,2024.0
8,9,1.502400e+11,"Товарищество с ограниченной ответственностью ""...",None,ТУРМАНОВ МАРАТ РАШИТОВИЧ,27.07.2023 года дело №2713-23-00-2/1498 решени...,None,NaN
9,10,1.501400e+11,"Товарищество с ограниченной ответственностью""M...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/2577,2025-12-08,2025.0
10,11,1.301400e+11,"Товарищество с ограниченной ответственностью ""...",None,БАКТЫГАЛИЕВ ЕЛДАР КАЙРАТОВИЧ,На основании Решении СМЭС ЗКО за исх\n№2713-21...,None,NaN
11,12,1.301400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,№2713-21-00-2/2121,2024-10-08,2024.0
12,13,1.212400e+11,"Товарищество с ограниченной ответственностью ""...",None,НАЗЫМОВ МАЛИК МУСАЕВИЧ,2713-25-00-2/255,2025-05-13,2025.0
13,14,1.210400e+11,"Товарищество с ограниченной ответственностью""I...",None,МУСАЕВ АЛИ АБДУКАРИМОВИЧ,2713-24-00-2/2166,2024-12-27,2024.0
14,15,1.208400e+11,"Товарищество с ограниченной ответственностью""S...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/2690,2025-12-19,2025.0
15,16,1.110400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУХАНБЕТЖАНОВ БЕКБОЛАТ ЕСАЕВИЧ,2713-24-00-2/2382,2026-06-22,2026.0
16,17,1.107400e+11,"Товарищество с ограниченной ответственностью""L...",None,КАРТБАЕВ ЕРЛАН БЕКМУРЗАЕВИЧ,Решение СМЭС по Актюбинской области за\n№1513-...,None,NaN
17,18,1.103400e+11,"Товарищество с ограниченной ответственностью""S...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2084,2024-10-08,2024.0
18,19,1.003400e+11,"Товарищество с ограниченной ответственностью""А...",None,НАГМЕТОВ ИСЛАМ ИБРАЕВИЧ,№2713-25-00-2/2295,2025-12-02,2025.0
19,20,9.104000e+10,"Товарищество с ограниченной ответственностью""G...",None,АКБУЛАТОВА ЯНА СЕЙЛХАНОВНА,None,None,NaN
20,21,8.054001e+10,"Товарищество с ограниченной ответственностью""C...",None,БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА,Решение СМЭС по ЗКО №2713-20-00-2/1484 от\n04....,None,NaN
21,22,8.024002e+10,"Товарищество с ограниченной ответственностью""К...",None,УТЕГЕНОВ БАКЫТЖАН МАГАУИЯНОВИЧ,Решение СМЭС № 2713-24-00-2/767 от 13.06.2024,None,NaN
22,23,6.094000e+10,"Товарищество с ограниченной ответственностью""L...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,Решение суда СМЭС ЗКО №2713-21-00-2/988 от\n1...,None,NaN
23,24,NaN,"Товарищество с ограниченной ответственностью""С...",None,ДАНИЛОВ СЕРГЕЙ АЛЕКСЕЕВИЧ,решение суда 2-527/09 от 27.04.09,None,NaN
24,25,5.054001e+10,"Товарищество с ограниченной ответственностью""Б...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2094,2024-12-27,2024.0
25,26,4.074101e+10,None,None,НУРГАЛИЕВ АСГАТ,решение СМЭС №02-10848-13,None,NaN
26,27,4.044004e+10,"Товарищество с ограниченной ответственностью""К...",None,КАДЫРОВ БИСЕМБАЙ КАИРЖАНОВИЧ,№ 2-861/07 от 06.07.07г.,None,NaN
27,29,9.801400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,2713-23-00-2/138,2024-10-08,2024.0
28,30,4.074002e+10,"товарищество с ограниченной ответственностью ""...",None,ГОЛОВАНОВА НАТАЛЬЯ НИКОЛАЕВНА,решение суда № 2-912/07 от 03.08.07г.,None,NaN
29,32,9.804400e+11,"Товарищество с ограниченной ответственностью""А...",None,КАЛШАБАЕВ ДОСЫМХАН ШЕРТАЕВИЧ,5265-24-00-2/3875,2024-12-27,2024.0
30,33,4.410052e+08,None,None,КИНЖИГАЛИЕВ СЕРИК САМИГУЛЛОВИЧ,7527-25-00-2/4263,2025-12-02,2025.0
31,35,1.034000e+10,"Товарищество с ограниченной ответственностью""С...",None,ТАЗИЕВА ТАТЬЯНА ТАЛГАТОВНА,Решение №7527-24-00-2/1902,None,NaN
32,36,8.400031e+08,"Товарищество с ограниченной ответственностью""Ж...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,Решение суда № 2713-21-00-2/1546 от 13.10.2021...,None,NaN
33,37,8.400038e+08,"Товарищество с ограниченной ответственностью""Т...",None,ОСПАНБЕКОВ АХАТ САПАРГАЛИЕВИЧ,Решение суда № 2713-21-00-2/2275 от 09.02.2022...,None,NaN
34,38,9.510410e+11,None,None,АНТОШ ЛАДИСЛАВ,None,None,NaN
35,40,4.034001e+10,"Товарищество с ограниченной ответственностью""П...",None,АМАНГАЛИЕВ АЛМАС СЕРИКОВИЧ,№2-91/15,None,NaN
36,41,9.903400e+11,"Товарищество с ограниченной ответственностью""З...",None,ДАВЛЕТОВА ГУЛЬДАРИЯ ТЕМИРБОЛАТОВНА,Решение СМЭС №2713-24-00-2/1263 от 9 июля 2024...,None,NaN
37,42,1.084002e+10,"Товарищество с ограниченной ответственностью""Т...",None,ДУЙСЕКЕНОВ ТАЛГАТ КАЙРЛИЕВИЧ,решение суда № 2-395/07 от 14.03.07г.,None,NaN
38,44,1.064000e+10,"Товарищество с ограниченной ответственностью""Р...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,решение СМЭС по г.Уральск №2713-22-00-2/2194,None,NaN
39,46,5.044001e+10,"Товарищество с ограниченной ответственностью""Б...",None,БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА,2713-24-002/2539,2024-12-27,2024.0
40,47,1.024000e+10,"Товарищество с ограниченной ответственностью ""...",None,ЛУКПАНОВ ЖЕКСЕН ИЗБАСХАНОВИЧ,решение СМЭС по ЗКО № 2-973/11 от 04.07.2011 г.,None,NaN
41,49,3.400016e+08,"Товарищество с ограниченной ответственностью""Г...",None,МУХАМАДЕЕВ АНВАР ВАВИЛЬЕВИЧ,решение суда № 2-3042/14,None,NaN
42,50,9.911400e+11,"Товарищество с ограниченной ответственностью ""...",None,САБЫРГАЛИЕВ НУРЛАН АРОНОВИЧ,2713-23-00-2/662,2024-10-08,2024.0
43,51,9.912400e+11,"Товарищество с ограниченной ответственностью""Р...",None,ПОБЕДИМОВ ОЛЕГ НИКОЛАЕВИЧ,решение суда №2-438/04,None,NaN
44,53,6.603073e+11,None,None,None,определение СМЭС по городу Уральск 12 августа...,None,NaN
45,54,9.802045e+11,None,None,None,2713-25-00-2/442,2025-07-09,2025.0
46,55,9.204175e+11,None,None,None,Решение СМЭС ЗКО № 2713-24-00-2/2338 от 15.10....,None,NaN
47,56,9.109234e+11,None,None,None,Решение СМЭС ЗКО №2713-24-00-2/664 от 29.04.20...,None,NaN
48,57,8.808293e+11,"ИП ""ХУСАИНОВ Ж.С""",None,None,На основании решения СМЭС ЗКО №2713-22-00-2/55...,None,NaN
49,58,7.905164e+11,None,None,None,"РЕШЕНИЕ СМЭС ЗКО от 4 апреля 2025 года, дело\n...",None,NaN
50,59,8.611073e+11,ИП ХАМИДОЛЛИН МЕЙРАМ САКЕНОВИЧ,None,None,№2713-22-00-2/2065,None,NaN
51,60,7.407283e+11,"ИП ""Габдулов А.Б.""",None,None,Решение СМЭС ЗКО №2713-23-00-2/71043 от\n07.0...,None,NaN
52,61,7.211273e+11,"ИП ""Сабанов Б. К""",None,None,Решение СМЭС ЗКО №2713-23-00-2/2507 от 14.11.2...,None,NaN
53,62,7.507053e+11,None,None,None,Решением СМЭС по ЗКО признан банкротам\n№2713-...,None,NaN
54,63,5.007103e+11,None,None,None,Решение СМЭС ЗКО №2713-23-00-2/650 от 26.05.2023,None,NaN
55,64,6.702174e+11,None,None,None,2713-25-00-2/2396,2025-12-03,2025.0

In [6]:
def sql(запрос):
    return pd.read_sql(запрос, conn)

In [7]:
sql("SELECT * FROM bankrupts")

,№,ИИН/БИН,Наименование налогоплательщика,ФИО налогоплательщика,ФИО руководителя,Номер решения суда,Дата решения суда,Год решения
0,1,2.310400e+11,"Товарищество с ограниченной ответственностью""Г...",None,ҚАЛИЕВ АЙБОЛАТ ҚҰРМАНҒАЛИҰЛЫ,2713-26-00-2/788,2026-06-22,2026.0
1,2,2.101400e+11,"Товарищество с ограниченной ответственностью""B...",None,САГИТОВ ИЛЬДАР РАСТАМОВИЧ,Решение СМЭС по ЗКО №2713-24-00-2/1831,None,NaN
2,3,2.001400e+11,"Товарищество с ограниченной ответственностью""Z...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/112,2026-03-20,2026.0
3,4,1.909400e+11,"Товарищество с ограниченной ответственностью""R...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-26-00-2/178,2026-06-18,2026.0
4,5,1.907400e+11,"Товарищество с ограниченной ответственностью""G...",None,КУРМАНГАЛИЕВ АЛДАН ХАБИБУЛЛОВИЧ,2713-22-00-2/1538,2024-10-08,2024.0
5,6,1.906400e+11,"Товарищество с ограниченной ответственностью ""...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2285,2024-10-08,2024.0
6,7,1.803400e+11,"Товарищество с ограниченной ответственностью""B...",None,АМАНГАЛИЕВ ЕРЛАН НУРЛАНОВИЧ,2713-26-00-2/339,2026-06-18,2026.0
7,8,1.709400e+11,"Товарищество с ограниченной ответственностью""Ч...",None,ЖАКАТАЕВ БАХЫТЖАН КАЙЫРЛИЕВИЧ,2713-24-00-2/1004,2024-10-08,2024.0
8,9,1.502400e+11,"Товарищество с ограниченной ответственностью ""...",None,ТУРМАНОВ МАРАТ РАШИТОВИЧ,27.07.2023 года дело №2713-23-00-2/1498 решени...,None,NaN
9,10,1.501400e+11,"Товарищество с ограниченной ответственностью""M...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/2577,2025-12-08,2025.0
10,11,1.301400e+11,"Товарищество с ограниченной ответственностью ""...",None,БАКТЫГАЛИЕВ ЕЛДАР КАЙРАТОВИЧ,На основании Решении СМЭС ЗКО за исх\n№2713-21...,None,NaN
11,12,1.301400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,№2713-21-00-2/2121,2024-10-08,2024.0
12,13,1.212400e+11,"Товарищество с ограниченной ответственностью ""...",None,НАЗЫМОВ МАЛИК МУСАЕВИЧ,2713-25-00-2/255,2025-05-13,2025.0
13,14,1.210400e+11,"Товарищество с ограниченной ответственностью""I...",None,МУСАЕВ АЛИ АБДУКАРИМОВИЧ,2713-24-00-2/2166,2024-12-27,2024.0
14,15,1.208400e+11,"Товарищество с ограниченной ответственностью""S...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-25-00-2/2690,2025-12-19,2025.0
15,16,1.110400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУХАНБЕТЖАНОВ БЕКБОЛАТ ЕСАЕВИЧ,2713-24-00-2/2382,2026-06-22,2026.0
16,17,1.107400e+11,"Товарищество с ограниченной ответственностью""L...",None,КАРТБАЕВ ЕРЛАН БЕКМУРЗАЕВИЧ,Решение СМЭС по Актюбинской области за\n№1513-...,None,NaN
17,18,1.103400e+11,"Товарищество с ограниченной ответственностью""S...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2084,2024-10-08,2024.0
18,19,1.003400e+11,"Товарищество с ограниченной ответственностью""А...",None,НАГМЕТОВ ИСЛАМ ИБРАЕВИЧ,№2713-25-00-2/2295,2025-12-02,2025.0
19,20,9.104000e+10,"Товарищество с ограниченной ответственностью""G...",None,АКБУЛАТОВА ЯНА СЕЙЛХАНОВНА,None,None,NaN
20,21,8.054001e+10,"Товарищество с ограниченной ответственностью""C...",None,БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА,Решение СМЭС по ЗКО №2713-20-00-2/1484 от\n04....,None,NaN
21,22,8.024002e+10,"Товарищество с ограниченной ответственностью""К...",None,УТЕГЕНОВ БАКЫТЖАН МАГАУИЯНОВИЧ,Решение СМЭС № 2713-24-00-2/767 от 13.06.2024,None,NaN
22,23,6.094000e+10,"Товарищество с ограниченной ответственностью""L...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,Решение суда СМЭС ЗКО №2713-21-00-2/988 от\n1...,None,NaN
23,24,NaN,"Товарищество с ограниченной ответственностью""С...",None,ДАНИЛОВ СЕРГЕЙ АЛЕКСЕЕВИЧ,решение суда 2-527/09 от 27.04.09,None,NaN
24,25,5.054001e+10,"Товарищество с ограниченной ответственностью""Б...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,2713-24-00-2/2094,2024-12-27,2024.0
25,26,4.074101e+10,None,None,НУРГАЛИЕВ АСГАТ,решение СМЭС №02-10848-13,None,NaN
26,27,4.044004e+10,"Товарищество с ограниченной ответственностью""К...",None,КАДЫРОВ БИСЕМБАЙ КАИРЖАНОВИЧ,№ 2-861/07 от 06.07.07г.,None,NaN
27,29,9.801400e+11,"Товарищество с ограниченной ответственностью""Б...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,2713-23-00-2/138,2024-10-08,2024.0
28,30,4.074002e+10,"товарищество с ограниченной ответственностью ""...",None,ГОЛОВАНОВА НАТАЛЬЯ НИКОЛАЕВНА,решение суда № 2-912/07 от 03.08.07г.,None,NaN
29,32,9.804400e+11,"Товарищество с ограниченной ответственностью""А...",None,КАЛШАБАЕВ ДОСЫМХАН ШЕРТАЕВИЧ,5265-24-00-2/3875,2024-12-27,2024.0
30,33,4.410052e+08,None,None,КИНЖИГАЛИЕВ СЕРИК САМИГУЛЛОВИЧ,7527-25-00-2/4263,2025-12-02,2025.0
31,35,1.034000e+10,"Товарищество с ограниченной ответственностью""С...",None,ТАЗИЕВА ТАТЬЯНА ТАЛГАТОВНА,Решение №7527-24-00-2/1902,None,NaN
32,36,8.400031e+08,"Товарищество с ограниченной ответственностью""Ж...",None,МУСАЛИМОВ ТИМУР БУЛАТОВИЧ,Решение суда № 2713-21-00-2/1546 от 13.10.2021...,None,NaN
33,37,8.400038e+08,"Товарищество с ограниченной ответственностью""Т...",None,ОСПАНБЕКОВ АХАТ САПАРГАЛИЕВИЧ,Решение суда № 2713-21-00-2/2275 от 09.02.2022...,None,NaN
34,38,9.510410e+11,None,None,АНТОШ ЛАДИСЛАВ,None,None,NaN
35,40,4.034001e+10,"Товарищество с ограниченной ответственностью""П...",None,АМАНГАЛИЕВ АЛМАС СЕРИКОВИЧ,№2-91/15,None,NaN
36,41,9.903400e+11,"Товарищество с ограниченной ответственностью""З...",None,ДАВЛЕТОВА ГУЛЬДАРИЯ ТЕМИРБОЛАТОВНА,Решение СМЭС №2713-24-00-2/1263 от 9 июля 2024...,None,NaN
37,42,1.084002e+10,"Товарищество с ограниченной ответственностью""Т...",None,ДУЙСЕКЕНОВ ТАЛГАТ КАЙРЛИЕВИЧ,решение суда № 2-395/07 от 14.03.07г.,None,NaN
38,44,1.064000e+10,"Товарищество с ограниченной ответственностью""Р...",None,МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА,решение СМЭС по г.Уральск №2713-22-00-2/2194,None,NaN
39,46,5.044001e+10,"Товарищество с ограниченной ответственностью""Б...",None,БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА,2713-24-002/2539,2024-12-27,2024.0
40,47,1.024000e+10,"Товарищество с ограниченной ответственностью ""...",None,ЛУКПАНОВ ЖЕКСЕН ИЗБАСХАНОВИЧ,решение СМЭС по ЗКО № 2-973/11 от 04.07.2011 г.,None,NaN
41,49,3.400016e+08,"Товарищество с ограниченной ответственностью""Г...",None,МУХАМАДЕЕВ АНВАР ВАВИЛЬЕВИЧ,решение суда № 2-3042/14,None,NaN
42,50,9.911400e+11,"Товарищество с ограниченной ответственностью ""...",None,САБЫРГАЛИЕВ НУРЛАН АРОНОВИЧ,2713-23-00-2/662,2024-10-08,2024.0
43,51,9.912400e+11,"Товарищество с ограниченной ответственностью""Р...",None,ПОБЕДИМОВ ОЛЕГ НИКОЛАЕВИЧ,решение суда №2-438/04,None,NaN
44,53,6.603073e+11,None,None,None,определение СМЭС по городу Уральск 12 августа...,None,NaN
45,54,9.802045e+11,None,None,None,2713-25-00-2/442,2025-07-09,2025.0
46,55,9.204175e+11,None,None,None,Решение СМЭС ЗКО № 2713-24-00-2/2338 от 15.10....,None,NaN
47,56,9.109234e+11,None,None,None,Решение СМЭС ЗКО №2713-24-00-2/664 от 29.04.20...,None,NaN
48,57,8.808293e+11,"ИП ""ХУСАИНОВ Ж.С""",None,None,На основании решения СМЭС ЗКО №2713-22-00-2/55...,None,NaN
49,58,7.905164e+11,None,None,None,"РЕШЕНИЕ СМЭС ЗКО от 4 апреля 2025 года, дело\n...",None,NaN
50,59,8.611073e+11,ИП ХАМИДОЛЛИН МЕЙРАМ САКЕНОВИЧ,None,None,№2713-22-00-2/2065,None,NaN
51,60,7.407283e+11,"ИП ""Габдулов А.Б.""",None,None,Решение СМЭС ЗКО №2713-23-00-2/71043 от\n07.0...,None,NaN
52,61,7.211273e+11,"ИП ""Сабанов Б. К""",None,None,Решение СМЭС ЗКО №2713-23-00-2/2507 от 14.11.2...,None,NaN
53,62,7.507053e+11,None,None,None,Решением СМЭС по ЗКО признан банкротам\n№2713-...,None,NaN
54,63,5.007103e+11,None,None,None,Решение СМЭС ЗКО №2713-23-00-2/650 от 26.05.2023,None,NaN
55,64,6.702174e+11,None,None,None,2713-25-00-2/2396,2025-12-03,2025.0

In [8]:
sql("""
SELECT "ИИН/БИН", "ФИО руководителя", "Год решения"
FROM bankrupts
""")

         ИИН/БИН                    ФИО руководителя  Год решения
0   2.310400e+11        ҚАЛИЕВ АЙБОЛАТ ҚҰРМАНҒАЛИҰЛЫ       2026.0
1   2.101400e+11           САГИТОВ ИЛЬДАР РАСТАМОВИЧ          NaN
2   2.001400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2026.0
3   1.909400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2026.0
4   1.907400e+11     КУРМАНГАЛИЕВ АЛДАН ХАБИБУЛЛОВИЧ       2024.0
5   1.906400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
6   1.803400e+11         АМАНГАЛИЕВ ЕРЛАН НУРЛАНОВИЧ       2026.0
7   1.709400e+11       ЖАКАТАЕВ БАХЫТЖАН КАЙЫРЛИЕВИЧ       2024.0
8   1.502400e+11            ТУРМАНОВ МАРАТ РАШИТОВИЧ          NaN
9   1.501400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2025.0
10  1.301400e+11        БАКТЫГАЛИЕВ ЕЛДАР КАЙРАТОВИЧ          NaN
11  1.301400e+11           МУСАЛИМОВ ТИМУР БУЛАТОВИЧ       2024.0
12  1.212400e+11              НАЗЫМОВ МАЛИК МУСАЕВИЧ       2025.0
13  1.210400e+11            МУСАЕВ АЛИ АБДУКАРИМОВИЧ       2024.0
14  1.208400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2025.0
15  1.110400e+11      МУХАНБЕТЖАНОВ БЕКБОЛАТ ЕСАЕВИЧ       2026.0
16  1.107400e+11         КАРТБАЕВ ЕРЛАН БЕКМУРЗАЕВИЧ          NaN
17  1.103400e+11       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
18  1.003400e+11             НАГМЕТОВ ИСЛАМ ИБРАЕВИЧ       2025.0
19  9.104000e+10          АКБУЛАТОВА ЯНА СЕЙЛХАНОВНА          NaN
20  8.054001e+10      БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА          NaN
21  8.024002e+10      УТЕГЕНОВ БАКЫТЖАН МАГАУИЯНОВИЧ          NaN
22  6.094000e+10           МУСАЛИМОВ ТИМУР БУЛАТОВИЧ          NaN
23           NaN           ДАНИЛОВ СЕРГЕЙ АЛЕКСЕЕВИЧ          NaN
24  5.054001e+10       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
25  4.074101e+10                    НУРГАЛИЕВ АСГАТ           NaN
26  4.044004e+10        КАДЫРОВ БИСЕМБАЙ КАИРЖАНОВИЧ          NaN
27  9.801400e+11           МУСАЛИМОВ ТИМУР БУЛАТОВИЧ       2024.0
28  4.074002e+10       ГОЛОВАНОВА НАТАЛЬЯ НИКОЛАЕВНА          NaN
29  9.804400e+11        КАЛШАБАЕВ ДОСЫМХАН ШЕРТАЕВИЧ       2024.0
30  4.410052e+08      КИНЖИГАЛИЕВ СЕРИК САМИГУЛЛОВИЧ       2025.0
31  1.034000e+10          ТАЗИЕВА ТАТЬЯНА ТАЛГАТОВНА          NaN
32  8.400031e+08           МУСАЛИМОВ ТИМУР БУЛАТОВИЧ          NaN
33  8.400038e+08       ОСПАНБЕКОВ АХАТ САПАРГАЛИЕВИЧ          NaN
34  9.510410e+11                     АНТОШ ЛАДИСЛАВ           NaN
35  4.034001e+10          АМАНГАЛИЕВ АЛМАС СЕРИКОВИЧ          NaN
36  9.903400e+11  ДАВЛЕТОВА ГУЛЬДАРИЯ ТЕМИРБОЛАТОВНА          NaN
37  1.084002e+10        ДУЙСЕКЕНОВ ТАЛГАТ КАЙРЛИЕВИЧ          NaN
38  1.064000e+10       МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА          NaN
39  5.044001e+10      БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА       2024.0
40  1.024000e+10        ЛУКПАНОВ ЖЕКСЕН ИЗБАСХАНОВИЧ          NaN
41  3.400016e+08         МУХАМАДЕЕВ АНВАР ВАВИЛЬЕВИЧ          NaN
42  9.911400e+11         САБЫРГАЛИЕВ НУРЛАН АРОНОВИЧ       2024.0
43  9.912400e+11           ПОБЕДИМОВ ОЛЕГ НИКОЛАЕВИЧ          NaN
44  6.603073e+11                                None          NaN
45  9.802045e+11                                None       2025.0
46  9.204175e+11                                None          NaN
47  9.109234e+11                                None          NaN
48  8.808293e+11                                None          NaN
49  7.905164e+11                                None          NaN
50  8.611073e+11                                None          NaN
51  7.407283e+11                                None          NaN
52  7.211273e+11                                None          NaN
53  7.507053e+11                                None          NaN
54  5.007103e+11                                None          NaN
55  6.702174e+11                                None       2025.0

In [9]:
sql("""
SELECT "ИИН/БИН", "ФИО руководителя", "Год решения"
FROM bankrupts
WHERE "Год решения" = 2024
""")

         ИИН/БИН                 ФИО руководителя  Год решения
0   1.907400e+11  КУРМАНГАЛИЕВ АЛДАН ХАБИБУЛЛОВИЧ       2024.0
1   1.906400e+11    МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
2   1.709400e+11    ЖАКАТАЕВ БАХЫТЖАН КАЙЫРЛИЕВИЧ       2024.0
3   1.301400e+11        МУСАЛИМОВ ТИМУР БУЛАТОВИЧ       2024.0
4   1.210400e+11         МУСАЕВ АЛИ АБДУКАРИМОВИЧ       2024.0
5   1.103400e+11    МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
6   5.054001e+10    МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА       2024.0
7   9.801400e+11        МУСАЛИМОВ ТИМУР БУЛАТОВИЧ       2024.0
8   9.804400e+11     КАЛШАБАЕВ ДОСЫМХАН ШЕРТАЕВИЧ       2024.0
9   5.044001e+10   БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА       2024.0
10  9.911400e+11      САБЫРГАЛИЕВ НУРЛАН АРОНОВИЧ       2024.0

In [10]:
sql("""Select "Год решения",
Count(*) from bankrupts
group by "Год решения" """)

   Год решения  Count(*)
0          NaN        33
1       2024.0        11
2       2025.0         7
3       2026.0         5

In [11]:
sql("""Select "ФИО руководителя",
Count(*) from bankrupts
group by "ФИО руководителя"
order by count(*) desc
limit 10
 """)

                 ФИО руководителя  Count(*)
0                            None        12
1   МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА         8
2       МУСАЛИМОВ ТИМУР БУЛАТОВИЧ         4
3  БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА         2
4    ҚАЛИЕВ АЙБОЛАТ ҚҰРМАНҒАЛИҰЛЫ         1
5  УТЕГЕНОВ БАКЫТЖАН МАГАУИЯНОВИЧ         1
6        ТУРМАНОВ МАРАТ РАШИТОВИЧ         1
7      ТАЗИЕВА ТАТЬЯНА ТАЛГАТОВНА         1
8       САГИТОВ ИЛЬДАР РАСТАМОВИЧ         1
9     САБЫРГАЛИЕВ НУРЛАН АРОНОВИЧ         1

In [12]:
sql("""Select "ФИО руководителя",
Count(*) from bankrupts
group by "ФИО руководителя"
having count(*) > 1
order by count(*) desc """)

                 ФИО руководителя  Count(*)
0                            None        12
1   МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА         8
2       МУСАЛИМОВ ТИМУР БУЛАТОВИЧ         4
3  БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА         2

In [13]:
sql("""Select "ФИО руководителя",
count(*) from bankrupts
where "ФИО руководителя" is not null
group by "ФИО руководителя"
having count(*) > 1
order by count(*) desc """)

                 ФИО руководителя  count(*)
0   МУКАНОВА УЛЬФАТ ХАБИБУЛЛАЕВНА         8
1       МУСАЛИМОВ ТИМУР БУЛАТОВИЧ         4
2  БУРХАНОВА ЭЛЬМИРА ЖАНГЕЛДИЕВНА         2

In [14]:
df = df.drop(columns=["ИИН руководителя", "РНН руководителя", "РНН"], errors="ignore")

In [15]:
df.columns.tolist()

['№',
 'ИИН/БИН',
 'Наименование  налогоплательщика',
 'ФИО налогоплательщика',
 'ФИО руководителя',
 'Номер решения суда',
 'Дата решения суда',
 'Год решения']

In [16]:
df.to_csv("bankrupts_zko_clean.csv", index=False, encoding="utf-8-sig")